load("../extdata/cc.Rdata")
corpus.cc<-generateCorpus(cc)
#print(lai(corpus.cc))
lai.cc<-LAI(corpus.cc)
expect_that(sort(names(lai.cc)), equals(c("a","b","c","d","e","f","g")))
#expect_that(as.numeric(lai(corpus.cc)), equals(c(0.2500,0.4750,0.4275,0.2025,0.2500,0.4750,0.4275)))
expect_equal(as.numeric(lai.cc["a"]),as.numeric(lai.cc["e"]))
expect_equal(as.numeric(lai.cc["b"]),as.numeric(lai.cc["f"]))
expect_equal(as.numeric(lai.cc["c"]),as.numeric(lai.cc["g"]))
expect_that(as.numeric(lai.cc["b"]),is_more_than(as.numeric(lai.cc["c"])))
expect_that(as.numeric(lai.cc["c"]),is_more_than(as.numeric(lai.cc["d"])))
